# Data Profiling

Melakukan profiling pada data Flood Prediction South Sulawesi menggunakan Polars dan DuckDB.

In [32]:
import os
import polars as pl
import duckdb

DATA_PATH = '../data/modis_flood_features.csv'

## Profiling menggunakan Polars

In [33]:
# Load data lazily
df_lazy = pl.scan_csv(DATA_PATH, ignore_errors=True)

# Tampilkan skema
print(df_lazy.collect_schema())

Schema({'date': String, 'lon': Float64, 'lat': Float64, 'flooded': Float64, 'jrc_perm_water': Float64, 'precip_1d': Float64, 'precip_3d': Float64, 'NDVI': Float64, 'NDWI': Float64, 'landcover': Float64, 'elevation': Float64, 'slope': Float64, 'aspect': Float64, 'upstream_area': Float64, 'TWI': Float64, 'target': Int64})

In [34]:
# Tampilkan beberapa baris pertama
df_lazy.head().collect()

shape: (5, 16)
┌────────────┬────────────┬───────────┬─────────┬───┬────────────┬─────────────┬──────────┬────────┐
│ date       ┆ lon        ┆ lat       ┆ flooded ┆ … ┆ aspect     ┆ upstream_ar ┆ TWI      ┆ target │
│ ---        ┆ ---        ┆ ---       ┆ ---     ┆   ┆ ---        ┆ ea          ┆ ---      ┆ ---    │
│ str        ┆ f64        ┆ f64       ┆ f64     ┆   ┆ f64        ┆ ---         ┆ f64      ┆ i64    │
│            ┆            ┆           ┆         ┆   ┆            ┆ f64         ┆          ┆        │
╞════════════╪════════════╪═══════════╪═════════╪═══╪════════════╪═════════════╪══════════╪════════╡
│ 2003-12-10 ┆ 120.478677 ┆ -6.495942 ┆ 1.0     ┆ … ┆ 270.0      ┆ 0.03199     ┆ 1.042098 ┆ 0      │
│ 2003-12-10 ┆ 120.480923 ┆ -6.495942 ┆ 1.0     ┆ … ┆ 236.480074 ┆ 0.03199     ┆ 1.042098 ┆ 0      │
│ 2003-12-10 ┆ 120.478677 ┆ -6.493697 ┆ 0.0     ┆ … ┆ 270.0      ┆ 0.03199     ┆ 1.042098 ┆ 0      │
│ 2003-12-10 ┆ 120.480923 ┆ -6.493697 ┆ 1.0     ┆ … ┆ 240.413746 ┆ 0.021235    ┆ 0.258796 ┆ 1      │
│ 2003-12-10 ┆ 120.478677 ┆ -6.491451 ┆ 0.0     ┆ … ┆ 270.0      ┆ 0.03199     ┆ 1.042098 ┆ 0      │
└────────────┴────────────┴───────────┴─────────┴───┴────────────┴─────────────┴──────────┴────────┘

In [35]:
# Deskripsi data (statistik)
df_lazy.collect().describe()

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ date      ┆ lon       ┆ lat       ┆ … ┆ aspect    ┆ upstream_ ┆ TWI       ┆ target   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ area      ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1025801   ┆ 1.025801e ┆ 1.025801e ┆ … ┆ 1.025801e ┆ 1.025801e ┆ 1.025801e ┆ 1.025801 │
│           ┆           ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 120.17780 ┆ -3.961987 ┆ … ┆ 155.00511 ┆ 16.332991 ┆ 2.843527  ┆ 0.045189 │
│           ┆           ┆ 8         ┆           ┆   ┆ 7         ┆           ┆           ┆          │
│ std       ┆ null      ┆ 0.52951   ┆ 1.018204  ┆ … ┆ 106.33727 ┆ 149.26224 ┆ 2.500571  ┆ 0.207719 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 7         ┆           ┆          │
│ min       ┆ 2003-12-1 ┆ 119.35353 ┆ -6.495942 ┆ … ┆ 0.0       ┆ 0.008497  ┆ 0.000023  ┆ 0.0      │
│           ┆ 0         ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 119.79146 ┆ -4.766685 ┆ … ┆ 63.489535 ┆ 0.023397  ┆ 0.933785  ┆ 0.0      │
│           ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 120.15303 ┆ -4.000872 ┆ … ┆ 153.37829 ┆ 0.08753   ┆ 2.119129  ┆ 0.0      │
│           ┆           ┆ 8         ┆           ┆   ┆ 8         ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 120.35740 ┆ -2.853274 ┆ … ┆ 243.54230 ┆ 0.58918   ┆ 4.174976  ┆ 0.0      │
│           ┆           ┆ 5         ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ max       ┆ 2015-02-0 ┆ 121.79021 ┆ -1.894322 ┆ … ┆ 359.34811 ┆ 5128.5278 ┆ 14.996599 ┆ 1.0      │
│           ┆ 5         ┆ 8         ┆           ┆   ┆ 3         ┆ 32        ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Profiling menggunakan DuckDB `SUMMARIZE`

In [36]:
# Menjalankan perintah SUMMARIZE pada file CSV dengan DuckDB
query = f"SUMMARIZE SELECT * FROM read_csv_auto('{DATA_PATH}')"
duckdb.query(query).df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,date,DATE,2003-12-10,2015-02-05,7,2008-04-07 17:08:34.285714,None,2004-05-07,2007-06-16,2013-01-03,1025801,0.0
1,lon,DOUBLE,119.353537330435,121.790217538609,978,120.17780767018337,0.5295104965429103,119.79282354256978,120.15265565170873,120.35692983308266,1025801,0.0
2,lat,DOUBLE,-6.49594239828929,-1.89432235538704,2049,-3.9619865334557076,1.0182037099318137,-4.771869029582089,-4.001037695362841,-2.85192288194953,1025801,0.0
3,flooded,DOUBLE,0.0,1.0,2,0.11205779678514644,0.3154377021902998,0.0,0.0,0.0,1025801,0.0
4,jrc_perm_water,DOUBLE,0.0,1.0,2,0.0932217847321264,0.2907431271567862,0.0,0.0,0.0,1025801,0.0
5,precip_1d,DOUBLE,0.0,107.288398742676,5669,11.898757013442728,14.388523849003391,0.0,7.893404223799392,20.10910395611454,1025801,0.0
6,precip_3d,DOUBLE,0.0,220.21907043457,9405,42.717387874977604,31.635748575183488,20.876724668476697,39.36308277930042,60.311907518136856,1025801,0.0
7,NDVI,DOUBLE,-2000.0,10000.0,25932,5995.309841795773,2020.9382019573575,4914.362273167685,6418.610499491676,7550.880334743448,1025801,0.0
8,NDWI,DOUBLE,-0.385959088802338,0.598126113414764,585997,0.24713965297360463,0.11698595463245536,0.18298698061021332,0.2550702551610587,0.326453433240434,1025801,0.0
9,landcover,DOUBLE,1.0,17.0,15,11.12831826055931,3.7623340536655445,9.0,12.0,14.0,1025801,0.0
10,elevation,DOUBLE,0.0,2694.0,2310,125.31491780569526,274.432429141249,10.835716957056361,24.52792711291132,90.4438766846493,1025801,0.0
11,slope,DOUBLE,0.0,26.7202548980713,76687,1.062714596026718,1.5976324630390448,0.25564092212780354,0.5019497662243064,1.1957867482923046,1025801,0.0
12,aspect,DOUBLE,0.0,359.348113230288,94169,155.00511701328196,106.33727544886982,63.61825724344746,152.75571438464868,245.9993914026418,1025801,0.0
13,upstream_area,DOUBLE,0.008497217670083,5128.52783203125,154214,16.33299110814641,149.26224728267357,0.022527526774164936,0.08813441463318353,0.5848178632776521,1025801,0.0
14,TWI,DOUBLE,2.25815411836372e-05,14.9965986646073,111827,2.843526746434928,2.500570869397118,0.9293522841159055,2.107718857246776,4.178764360431157,1025801,0.0
15,target,BIGINT,0,1,2,0.04518907663377205,0.20771871858017021,0,0,0,1025801,0.0